#!/usr/bin/env bash
usage=$(df / | awk 'NR==2 {print $5}' | tr -d '%')
if [ "$usage" -gt 80 ]; then
    echo -e "Warning: Disk usage is at \e[38;5;196m${usage}%!"
    echo -e "\033[037m"
elif [ "$usage" -gt 70 ]; then
    echo -e "Disk usage is at \e[38;5;214m${usage}%!"
    echo -e "\033[037m"
    echo "your are good but be prepare to make free some space " 
else
    echo -e "Disk usage is only \e[38;5;40m${usage}%!"
    echo -e "\033[037m"
    echo "Your are good for a little more"
# fi